### PR TITLE
Added sChinese translation plus minor fixes.

### PR DESCRIPTION
**Pull request by gswvmware**
Added sChinese localization strings.
Fixed some outdated formats.
Removed a dupe key.
Added missing keys for quest title/description.

### CODE REVIEW

**Comment by arramus** [comment]
It is old format, yes. It has some punctuation to fix. A22 won't be long.
I pushed the A21-Preppocalypse-sChinese as a modlet to post load. Feel free to take care of it. Once the game is Gold it can be fully merged. Please check the end of Line 25 ,,

**Comment by gswvmware** [comment]
Ahh, thanks.
I removed the extra comma in line 25.
Is there a tool to edit/check localization files? Since i've been editing it manually with notepad++. (And SDX Mod Helper, the only tool i can find that seems helpful for this work, it's download link doesn't work for me) I'm not sure if you were checking every single comma one by one which sure would not be fun.
I'm new to github and 7d2d modding community so I don't know if there's anything more i can do. To where you pushed A21-Preppocalypse-sChinese? Should I close this pull request?
Anyway thank you for making this amazing mod.

Annnd... I know the part of extra keys of quest names/descriptions looks quite messy.
Should I post another version of localization.txt without this part?

**Comment by arramus** [comment]
I am not aware of any specific community tools to assist with localization files. However, one mod maker suggested to use GPT to write it. The instructions were given to another mod maker as 'Give it a header format and an example of data under that header and it will accurately add all specified language entries.' I have not attempted to follow these instructions but the recipient was happy with the results. Up to now, I have checked Localization manually. 

The formatting can be tedious, and has changed a few times throughout the Alpha history with A20 to A21 being another change. A lot of modders use their own header formatting. In the case of the Wasteland Mod it is simply 'Key,English' with post loading submissions for anyone in the community who wishes to support and expand.

**Comment by arramus** [comment]
It is best to close this pull request for now, if you don't mind. If there are any changes in the future, it would generally require another language update for additions soon after, and those will ultimately get passed along to Mod Launcher end users. They can get a bit testy about such things where they attempt to match Git versions for their communities. The A21-Preppocalypse-sChinese post loading mod can be posted in the main forum area and be available specifically for the community that can benefit from it. Those updates can be independent as and when required.

**Comment by arramus** [comment]
There should be a pending invite to collaborate on the A21-Preppocalypse-sChinese in your email box, or Github messages. Feel free to add this modlet to your own individual Github repo area as a standalone as your own project, or update the version currently there. If you opt to add it to your own Github, you are welcome to take guardianship of it and I can remove the version I hold. Either way, a version can be shared in the main forum posting for others to benefit from it. I shall cross reference any primary things such as changing " to "", or as suggested in your own recommendations '. Some missing the " altogether are actually missing them in the main game as well, and serve to be place markers for when the game finally goes Gold, at which point they can be posted as bugs in the official forum.

**Comment by gswvmware** [comment]
Wow, thanks for the thorough guide!
I understood about that software that translates with the help of GPT, and I used GPT in the translation process, but I still did some manual translations and playtesting to make sure the text was consistent and the translation matched the game content. I realize now though that I could have avoided a lot of formatting issues by using that software.
Thanks again for the introduction to the 7d2d modding community and github, I'll look into what I can do.

**Comment by arramus** [comment]
Consider visiting the Guppy's Unofficial 7D2D Discord if you would like to get more involved with the community. It is quite an eclectic and international gathering of modders and community members who are interested in how we can expand the base game. There's a lot to learn there, and share, depending on your own specialties. ^^

https://discord.com/invite/3aWeEGrjJK

**Pull request closed without merging**
